name: jokui_video
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # json 序列化 https://github.com/dart-lang/json_serializable
  json_annotation: ^3.0.0
  # 视频缩略图 https://github.com/justsoft/video_thumbnail
  # video_thumbnail: ^0.2.0
  # m3u8 播放器
  # chewie: ^0.9.10
  webview_flutter: ^0.3.19+5
  # https://github.com/flutterchina/dio
  dio: ^3.0.9
  cached_network_image: ^2.0.0
  pull_to_refresh: ^1.6.1
  flutter_swiper: ^1.1.6
  # m3u8 播放器
  video_player: ^0.10.8+1
  flutter_ijkplayer: ^0.3.5+1
  # 动态权限 https://github.com/baseflowit/flutter-permission-handler
  permission_handler: ^4.0.0
  path_provider: ^1.6.0
  # 屏幕适配
  flustars: ^0.2.6+1
  # 解析xml数据
  xml_parser: ^0.1.2
  # 状态管理
  provider: ^4.0.5
  # 提示框
  oktoast: ^2.2.0
  package_info: ^0.4.0+13
  # 使用第三方软件打开文件 https://github.com/crazecoder/open_file
  open_file: ^2.0.3
  # 打电话、打开第三方软件 https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
  url_launcher: ^5.4.1
  # 文本编辑 https://github.com/flutter/flutter_markdown
  flutter_markdown: ^0.3.5
  flutter_inappwebview: ^3.3.0+3
  web_socket_channel: ^1.1.0
  # 视频处理插件 https://github.com/tanersener/flutter-ffmpeg
  # flutter_ffmpeg: ^0.2.10
  extended_image: any
  # 清除缓存 https://github.com/Baseflow/flutter_cache_manager
  flutter_cache_manager: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/video/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
