// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'video_list.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

VideoDetail _$VideoDetailFromJson(Map<String, dynamic> json) {
  return VideoDetail(
    json['vod_id'] as String,
    json['type_id'] as int,
    json['type_id_1'] as int,
    json['group_id'] as int,
    json['vod_name'] as String,
    json['vod_sub'] as String,
    json['vod_en'] as String,
    json['vod_status'] as int,
    json['vod_letter'] as String,
    json['vod_color'] as String,
    json['vod_tag'] as String,
    json['vod_class'] as String,
    json['vod_pic'] as String,
    json['vod_pic_thumb'] as String,
    json['vod_pic_slide'] as String,
    json['vod_actor'] as String,
    json['vod_director'] as String,
    json['vod_writer'] as String,
    json['vod_behind'] as String,
    json['vod_blurb'] as String,
    json['vod_remarks'] as String,
    json['vod_pubdate'] as String,
    json['vod_total'] as int,
    json['vod_serial'] as String,
    json['vod_tv'] as String,
    json['vod_weekday'] as String,
    json['vod_area'] as String,
    json['vod_lang'] as String,
    json['vod_year'] as String,
    json['vod_version'] as String,
    json['vod_state'] as String,
    json['vod_author'] as String,
    json['vod_jumpurl'] as String,
    json['vod_tpl'] as String,
    json['vod_tpl_play'] as String,
    json['vod_tpl_down'] as String,
    json['vod_isend'] as int,
    json['vod_lock'] as int,
    json['vod_level'] as int,
    json['vod_copyright'] as int,
    json['vod_points'] as int,
    json['vod_points_play'] as int,
    json['vod_points_down'] as int,
    json['vod_hits'] as int,
    json['vod_hits_day'] as int,
    json['vod_hits_week'] as int,
    json['vod_hits_month'] as int,
    json['vod_duration'] as String,
    json['vod_up'] as int,
    json['vod_down'] as int,
    json['vod_score'] as String,
    json['vod_score_all'] as int,
    json['vod_score_num'] as int,
    json['vod_time'] as String,
    json['vod_time_add'] as int,
    json['vod_time_hits'] as int,
    json['vod_time_make'] as int,
    json['vod_trysee'] as int,
    json['vod_douban_id'] as int,
    json['vod_douban_score'] as String,
    json['vod_reurl'] as String,
    json['vod_rel_vod'] as String,
    json['vod_rel_art'] as String,
    json['vod_pwd'] as String,
    json['vod_pwd_url'] as String,
    json['vod_pwd_play'] as String,
    json['vod_pwd_play_url'] as String,
    json['vod_pwd_down'] as String,
    json['vod_pwd_down_url'] as String,
    json['vod_content'] as String,
    json['vod_play_from'] as String,
    json['vod_play_server'] as String,
    json['vod_play_note'] as String,
    json['vod_play_url'] as String,
    json['vod_down_from'] as String,
    json['vod_down_server'] as String,
    json['vod_down_note'] as String,
    json['vod_down_url'] as String,
    json['type_name'] as String,
    json['url'] as String,
    json['status'] != null ? json['status'] as bool : true,
    json['key'],
    (json['list'] as List)
        ?.map((e) =>
            e == null ? null : VideoAttr.fromJson(e as Map<String, dynamic>))
        ?.toList(),
  );
}

Map<String, dynamic> _$VideoDetailToJson(VideoDetail instance) =>
    <String, dynamic>{
      'vod_id': instance.vodId,
      'type_id': instance.typeId,
      'type_id_1': instance.typeId1,
      'group_id': instance.groupId,
      'vod_name': instance.vodName,
      'vod_sub': instance.vodSub,
      'vod_en': instance.vodEn,
      'vod_status': instance.vodStatus,
      'vod_letter': instance.vodLetter,
      'vod_color': instance.vodColor,
      'vod_tag': instance.vodTag,
      'vod_class': instance.vodClass,
      'vod_pic': instance.vodPic,
      'vod_pic_thumb': instance.vodPicThumb,
      'vod_pic_slide': instance.vodPicSlide,
      'vod_actor': instance.vodActor,
      'vod_director': instance.vodDirector,
      'vod_writer': instance.vodWriter,
      'vod_behind': instance.vodBehind,
      'vod_blurb': instance.vodBlurb,
      'vod_remarks': instance.vodRemarks,
      'vod_pubdate': instance.vodPubdate,
      'vod_total': instance.vodTotal,
      'vod_serial': instance.vodSerial,
      'vod_tv': instance.vodTv,
      'vod_weekday': instance.vodWeekday,
      'vod_area': instance.vodArea,
      'vod_lang': instance.vodLang,
      'vod_year': instance.vodYear,
      'vod_version': instance.vodVersion,
      'vod_state': instance.vodState,
      'vod_author': instance.vodAuthor,
      'vod_jumpurl': instance.vodJumpurl,
      'vod_tpl': instance.vodTpl,
      'vod_tpl_play': instance.vodTplPlay,
      'vod_tpl_down': instance.vodTplDown,
      'vod_isend': instance.vodIsend,
      'vod_lock': instance.vodLock,
      'vod_level': instance.vodLevel,
      'vod_copyright': instance.vodCopyright,
      'vod_points': instance.vodPoints,
      'vod_points_play': instance.vodPointsPlay,
      'vod_points_down': instance.vodPointsDown,
      'vod_hits': instance.vodHits,
      'vod_hits_day': instance.vodHitsDay,
      'vod_hits_week': instance.vodHitsWeek,
      'vod_hits_month': instance.vodHitsMonth,
      'vod_duration': instance.vodDuration,
      'vod_up': instance.vodUp,
      'vod_down': instance.vodDown,
      'vod_score': instance.vodScore,
      'vod_score_all': instance.vodScoreAll,
      'vod_score_num': instance.vodScoreNum,
      'vod_time': instance.vodTime,
      'vod_time_add': instance.vodTimeAdd,
      'vod_time_hits': instance.vodTimeHits,
      'vod_time_make': instance.vodTimeMake,
      'vod_trysee': instance.vodTrysee,
      'vod_douban_id': instance.vodDoubanId,
      'vod_douban_score': instance.vodDoubanScore,
      'vod_reurl': instance.vodReurl,
      'vod_rel_vod': instance.vodRelVod,
      'vod_rel_art': instance.vodRelArt,
      'vod_pwd': instance.vodPwd,
      'vod_pwd_url': instance.vodPwdUrl,
      'vod_pwd_play': instance.vodPwdPlay,
      'vod_pwd_play_url': instance.vodPwdPlayUrl,
      'vod_pwd_down': instance.vodPwdDown,
      'vod_pwd_down_url': instance.vodPwdDownUrl,
      'vod_content': instance.vodContent,
      'vod_play_from': instance.vodPlayFrom,
      'vod_play_server': instance.vodPlayServer,
      'vod_play_note': instance.vodPlayNote,
      'vod_play_url': instance.vodPlayUrl,
      'vod_down_from': instance.vodDownFrom,
      'vod_down_server': instance.vodDownServer,
      'vod_down_note': instance.vodDownNote,
      'vod_down_url': instance.vodDownUrl,
      'type_name': instance.typeName,
      'url': instance.url,
      'status': instance.status,
      'key': instance.key,
      'list': instance.list,
    };

VideoList _$VideoListFromJson(Map<String, dynamic> json) {
    return VideoList(
      json['title'] as String,
      json['scope'] as String,
      json['type'] as String,
      json['census'] as String,
      json['tag'] as String,
      json['href'] as String,
      json['url'] as String,
      json['status'] != null ? json['status'] as bool : false,
    );
}
Map<String, dynamic> _$VideoListToJson(VideoList instance) => <String, dynamic>{
      'title' : instance.title,
      'scope' : instance.scope,
      'type'  : instance.type,
      'census': instance.census,
      'tag'   : instance.tag,
      'href'  : instance.href,
      'url'   : instance.url,
      'status': instance.status,
    };
